runtime: python
env: standard
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# beta_settings:
#     cloud_sql_instances: "advisor-group:us-central1:advisor-group-database"